# Eat Safe, Love

## Notebook Set Up

In [38]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd
from pymongo import UpdateOne

In [24]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [25]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [26]:
# review the collections in our database
pprint(db.list_collection_names())

['establishments']

In [27]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [28]:
#Query the establishments that have a hygiene score equal to 20
query = {'scores.Hygiene': 20}

# Use count_documents to display the number of documents in the result
count= establishments.count_documents(query)

# Display the first document in the results using pprint
first_document = establishments.find_one(query)

pprint(count)
pprint(first_document)

41
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': '0',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('65779eb472e86bcdb56e08f2'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [29]:
hygiene_20 = establishments.find(query)

In [30]:
# Convert the result to a Pandas DataFrame
df = pd.DataFrame(hygiene_20)

# Display the number of rows in the DataFrame
number_rows= len(df)
pprint(f'Number of Rows:{number_rows}')

# Display the first 10 rows of the DataFrame
first_10= df.head(10)
first_10

'Number of Rows:41'

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,65779eb472e86bcdb56e08f2,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,http://www.eastbourne.gov.uk/foodratings,Customerfirst@eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,65779eb472e86bcdb56e0c73,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,65779eb572e86bcdb56e0f7d,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,65779eb572e86bcdb56e116b,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.10202, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,65779eb572e86bcdb56e117a,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.101446, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,65779eb572e86bcdb56e1b19,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.736349, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,65779eb572e86bcdb56e1d3a,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.7121671, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,65779eb772e86bcdb56e3265,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,http://www.rochford.gov.uk,customerservices@rochford.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.602364, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,65779eb772e86bcdb56e36a9,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,http://www.sevenoaks.gov.uk/,environmental.health@sevenoaks.gov.uk,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.146449998021126, 'latitude': 5...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,65779eb872e86bcdb56e3ebb,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,http://www.basildon.gov.uk,ehs@basildon.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.462307, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [39]:
establishments.update_many({
    'RatingValue': {'$type': 'number'},},
    [{"$set": {"RatingValue": {"$toInt": "$RatingValue"}}}])

In [40]:
new_types= establishments.find_one()
new_types

{'_id': ObjectId('65779eb072e86bcdb56dedc0'),
 'FHRSID': 1043695,
 'ChangesByServerID': 0,
 'LocalAuthorityBusinessID': 'PI/000073616',
 'BusinessName': 'The Pavilion',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'AddressLine1': 'East Cliff Pavilion',
 'AddressLine2': 'Wear Bay Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'PostCode': 'CT19 6BL',
 'Phone': '',
 'RatingValue': 5,
 'RatingKey': 'fhrs_5_en-gb',
 'RatingDate': '2018-04-04T00:00:00',
 'LocalAuthorityCode': '188',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'scores': {'Hygiene': 5, 'Structural': 5, 'ConfidenceInManagement': 5},
 'SchemeType': 'FHRS',
 'geocode': {'longitude': 1.195625, 'latitude': 51.083812},
 'RightToReply': '',
 'Distance': 4591.765489457773,
 'NewRatingPending': False,
 'meta': {'dataSource': None,
  'extractDate': '0001-01-01T00:00:00',
  'itemCount': 0,
  'returncode': None,
  'totalCount': 0,
  'totalPages': 0,
  'pageSize': 0,
  'pageNumber': 0},
 'links': [{'rel': 'self',
   'href': 'https://api.ratings.food.gov.uk/establishments/1043695'}]}

In [41]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query_2 = {'LocalAuthorityName': 'London', 'RatingValue': {'$gte': 4}}
list(establishments.find(query))

# Use count_documents to display the number of documents in the result

count= establishments.count_documents(query_2)

# Display the first document in the results using pprint
result_2 = establishments.find_one(query_2)

pprint(f'Count: {count}')
pprint(result_2)

'Count: 0'
None

In [42]:
# Convert the result to a Pandas DataFrame
london_df= pd.DataFrame(result_2)

# Display the number of rows in the DataFrame
number_rows= london_df.shape[0]
pprint(f'Number of Rows:{number_rows}')

# Display the first 10 rows of the DataFrame
first_10= london_df.head(10)
print(first_10)

'Number of Rows:0'
Empty DataFrame
Columns: []
Index: []

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [47]:
#Penang Flavours Location
# Search within 0.01 degree on either side of the latitude and longitude.

degree_search = 0.01
penang_flavours_location = establishments.find_one(
    {'BusinessName': 'Penang Flavours'},
    {'geocode.latitude': 1, 'geocode.longitude': 1})


latitude_penang = penang_flavours_location['geocode']['latitude'] 
longitude_penang = penang_flavours_location['geocode']['longitude']

latitude_penang_range = {
    "$gte": latitude_penang - 0.01,
    "$lte": latitude_penang + 0.01}

longitude_penang_range = {
    "$gte": longitude_penang - 0.01,
    "$lte": longitude_penang + 0.01}


print(latitude_penang_range)
print(longitude_penang_range)

{'$gte': 51.480142, '$lte': 51.500142}
{'$gte': 0.07384, '$lte': 0.09383999999999999}

In [100]:
# Rating value must equal 5
# Sort by hygiene score

result_penang = establishments.find({       
        "RatingValue": 5}).sort([("scores.Hygiene", 1)]).limit(5)

result_penang

In [101]:
# Convert result to Pandas DataFrame
result_penang_df= pd.DataFrame(result_penang)
result_penang_df

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,65779eb072e86bcdb56dedd0,1423242,0,PI/000078141,Little Rock,Other catering premises,7841,Folkestone Harbour,Harbour Approach Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': 1.18590330311705, 'latitude': 51...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,65779eb072e86bcdb56dedc6,289560,0,PI/000039927,Mariner,Pub/bar/nightclub,7843,16 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,65779eb072e86bcdb56dedc8,344689,0,PI/000002095,Folkestone Trawlers Shop,Retailers - other,4613,1 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,65779eb072e86bcdb56dedcd,1071930,0,PI/000076531,The Club Hut,Pub/bar/nightclub,7843,Folkestone Harbour,Harbour Approach Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.18590330311705, 'latitude': 51...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,65779eb072e86bcdb56dedc9,894592,0,PI/000074396,Docker,Retailers - other,4613,Folkestone Harbour,Harbour Approach Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.18590330311705, 'latitude': 51...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [91]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query= {'$match':{'scores.Hygiene': 0}}

# 2. Groups the matches by Local Authority
group_query= [{'$group':{'_id':'$LocalAuthorityName','conteo':{'$sum':1}}}]
                        
# 3. Sorts the matches from highest to lowest
sort_query= {'$sort': {'conteo': -1, '_id':1}}

# Create the pipeline
pipeline = [match_query, group_query[0],sort_query]

# Aggregate using the pipeline
result = list(establishments.aggregate(pipeline))

result

[{'_id': 'Thanet', 'conteo': 1130},
 {'_id': 'Greenwich', 'conteo': 882},
 {'_id': 'Maidstone', 'conteo': 713},
 {'_id': 'Newham', 'conteo': 711},
 {'_id': 'Swale', 'conteo': 686},
 {'_id': 'Chelmsford', 'conteo': 680},
 {'_id': 'Medway', 'conteo': 672},
 {'_id': 'Bexley', 'conteo': 607},
 {'_id': 'Southend-On-Sea', 'conteo': 586},
 {'_id': 'Tendring', 'conteo': 542},
 {'_id': 'Colchester', 'conteo': 498},
 {'_id': 'Tunbridge Wells', 'conteo': 491},
 {'_id': 'Folkestone and Hythe', 'conteo': 480},
 {'_id': 'Eastbourne', 'conteo': 478},
 {'_id': 'Hastings', 'conteo': 464},
 {'_id': 'Bromley', 'conteo': 460},
 {'_id': 'Ashford', 'conteo': 427},
 {'_id': 'Havering', 'conteo': 397},
 {'_id': 'Dartford', 'conteo': 383},
 {'_id': 'Braintree', 'conteo': 382},
 {'_id': 'Basildon', 'conteo': 362},
 {'_id': 'Gravesham', 'conteo': 339},
 {'_id': 'Tonbridge and Malling', 'conteo': 325},
 {'_id': 'Thurrock', 'conteo': 313},
 {'_id': 'Barking and Dagenham', 'conteo': 301},
 {'_id': 'Canterbury City', 'conteo': 298},
 {'_id': 'Brentwood', 'conteo': 285},
 {'_id': 'Castle Point', 'conteo': 281},
 {'_id': 'Harlow', 'conteo': 274},
 {'_id': 'Uttlesford', 'conteo': 251},
 {'_id': 'Lewes', 'conteo': 250},
 {'_id': 'Sevenoaks', 'conteo': 223},
 {'_id': 'Maldon', 'conteo': 197},
 {'_id': 'East Hertfordshire', 'conteo': 189},
 {'_id': 'Rochford', 'conteo': 187},
 {'_id': 'Redbridge', 'conteo': 182},
 {'_id': 'Epping Forest', 'conteo': 180},
 {'_id': 'East Suffolk', 'conteo': 159},
 {'_id': 'Waltham Forest', 'conteo': 110},
 {'_id': 'Babergh', 'conteo': 97},
 {'_id': 'Wealden', 'conteo': 93},
 {'_id': 'Rother', 'conteo': 80},
 {'_id': 'Lewisham', 'conteo': 65},
 {'_id': 'Tandridge', 'conteo': 42},
 {'_id': 'City of London Corporation', 'conteo': 28},
 {'_id': 'Ipswich', 'conteo': 21},
 {'_id': 'Tower Hamlets', 'conteo': 9},
 {'_id': 'North Hertfordshire', 'conteo': 6},
 {'_id': 'Mid Sussex', 'conteo': 5},
 {'_id': 'Broxbourne', 'conteo': 1},
 {'_id': 'Dorset', 'conteo': 1},
 {'_id': 'Kensington and Chelsea', 'conteo': 1},
 {'_id': 'North Norfolk', 'conteo': 1},
 {'_id': 'Reading', 'conteo': 1},
 {'_id': 'Sunderland', 'conteo': 1}]

In [93]:
# Convert the result to a Pandas DataFrame
df= pd.DataFrame(result)

# Display the number of rows in the DataFrame
num_rows = len(df)
print(num_rows)

# Display the first 10 rows of the DataFrame
df.head(10)

55

               _id  conteo
0           Thanet    1130
1        Greenwich     882
2        Maidstone     713
3           Newham     711
4            Swale     686
5       Chelmsford     680
6           Medway     672
7           Bexley     607
8  Southend-On-Sea     586
9         Tendring     542